export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER"; 
export const UNSET_DISABLED_FLAG = "UNSET_DISABLED_FLAG";
export const SET_DISABLED_FLAG = "SET_DISABLED_FLAG";